version: '2'

services:
  app:
    image: 'backendtask1.0:latest'
    build:
      context: .
    ports:
      - 8080:8080
    container_name: backendtask
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdb:5432/articleService
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: pgdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0
      - POSTGRES_DB=articleService